const places={'กรุงเทพมหานคร':[13.7563,100.5018],'ชลบุรี':[13.3611,100.9847],'ระยอง':[12.6814,101.2816],'เชียงใหม่':[18.7883,98.9853],'ขอนแก่น':[16.4322,102.8236],'ภูเก็ต':[7.8804,98.3923],'นครราชสีมา':[14.9799,102.0978],'สุราษฎร์ธานี':[9.1382,99.3217]};
const map=L.map('map').setView([13.5,101],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);
const stations=L.layerGroup().addTo(map),rain=L.layerGroup(),risk=L.layerGroup();let currentMarker;
Object.entries(places).forEach(([name,p])=>{let m=L.circleMarker(p,{radius:5,color:'#8dd7ff',weight:2,fillColor:'#0b79d0',fillOpacity:1});m.bindTooltip(name);m.on('click',()=>load(name,p[0],p[1]));stations.addLayer(m)});
[['ชลบุรี',13.3611,100.9847],['ระยอง',12.6814,101.2816],['กรุงเทพมหานคร',13.7563,100.5018]].forEach(x=>risk.addLayer(L.circle([x[1],x[2]],{radius:30000,color:'#ff795d',fillColor:'#ff795d',fillOpacity:.08,weight:2}).bindTooltip('พื้นที่เฝ้าระวังตัวอย่าง')));
[[16.5,101.8],[13.3,101],[12.2,99.7],[17.2,99.4]].forEach(p=>rain.addLayer(L.circle(p,{radius:45000,color:'#27bdd7',fillColor:'#27bdd7',fillOpacity:.18,weight:0}).bindTooltip('ฝนตัวอย่าง — ยังไม่ใช่เรดาร์จริง')));
function icon(c){return c===0?'☀️':[1,2,3].includes(c)?'⛅':[95,96,99].includes(c)?'⛈️':'🌧️'}
function text(c){if(c===0)return'ท้องฟ้าแจ่มใส';if([1,2,3].includes(c))return'มีเมฆบางส่วน';if([45,48].includes(c))return'มีหมอก';if([51,53,55,56,57].includes(c))return'ฝนปรอย';if([61,63,65,66,67,80,81,82].includes(c))return'มีฝนตก';if([95,96,99].includes(c))return'ฝนฟ้าคะนอง';return'ไม่ทราบสภาพอากาศ'}
async function load(name,lat,lon){document.getElementById('place').textContent=name;map.setView([lat,lon],9);if(currentMarker)map.removeLayer(currentMarker);currentMarker=L.circleMarker([lat,lon],{radius:9,color:'#fff',weight:3,fillColor:'#1185e7',fillOpacity:1}).addTo(map);try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,weather_code&hourly=temperature_2m,precipitation_probability,weather_code&forecast_days=2&timezone=Asia%2FBangkok`;let d=await fetch(u).then(r=>r.json()),c=d.current;temp.textContent=Math.round(c.temperature_2m);hum.textContent=Math.round(c.relative_humidity_2m)+'%';wind.textContent=Math.round(c.wind_speed_10m)+' กม./ชม.';rain.textContent=Math.round(c.precipitation)+' มม.';condition.textContent=text(c.weather_code);icon.textContent=icon(c.weather_code);alert.textContent=c.precipitation>=10?'พบฝนค่อนข้างมาก ควรติดตามสถานการณ์':'ยังไม่พบฝนหนักจากข้อมูลพยากรณ์';risk.textContent=c.precipitation>=10?'เฝ้าระวัง':'ปกติ';let h=hours;h.innerHTML='';let now=Date.now(),s=d.hourly.time.findIndex(t=>new Date(t).getTime()>=now);if(s<0)s=0;for(let i=s;i<s+8;i++){let dt=new Date(d.hourly.time[i]);h.insertAdjacentHTML('beforeend',`<div class="hour"><small>${dt.toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</small><strong>${Math.round(d.hourly.temperature_2m[i])}°</strong><em>ฝน ${d.hourly.precipitation_probability[i]||0}%</em></div>`)}updated.textContent=' • '+new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}catch(e){condition.textContent='โหลดข้อมูลไม่สำเร็จ'}}
document.getElementById('searchBtn').onclick=()=>{let q=search.value.trim(),k=Object.keys(places).find(x=>x.includes(q)||q.includes(x));if(k)load(k,...places[k]);else alert('ยังไม่มีจังหวัดนี้ในรายการทดลอง')};
search.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('searchBtn').click()});
plus.onclick=()=>map.zoomIn();minus.onclick=()=>map.zoomOut();home.onclick=()=>map.setView([13.5,101],6);
locate.onclick=()=>map.locate({setView:true,maxZoom:12});map.on('locationfound',e=>load('ตำแหน่งของฉัน',e.latlng.lat,e.latlng.lng));
stations.on?0:0;
document.getElementById('stations').onchange=e=>e.target.checked?map.addLayer(stations):map.removeLayer(stations);
document.getElementById('rainDemo').onchange=e=>e.target.checked?map.addLayer(rain):map.removeLayer(rain);
document.getElementById('riskDemo').onchange=e=>e.target.checked?map.addLayer(risk):map.removeLayer(risk);
document.querySelectorAll('.ready').forEach(x=>x.onchange=()=>{let a=[...document.querySelectorAll('.ready')];score.textContent=Math.round(a.filter(x=>x.checked).length/a.length*100)+'%'});
load('กรุงเทพมหานคร',13.7563,100.5018);